export const seoConfig = {
  defaultTitle: "MVPReady - From Idea to MVP",
  titleTemplate: "%s | MVPReady",
  defaultKeywords: [
    "best MVP development agency",
    "MVP development agency",
    "startup MVP developers",
    "SaaS MVP development",
    "SaaS MVP builders",
    "AI MVP development company",
    "AI startup developers",
    "product engineering partner",
    "premium MVP development",
    "scalable MVP development",
    "investor-ready MVP",
    "non-technical founder MVP",
    "startup product engineering",
    "premium startup engineering partner",
    "web app MVP development",
    "product design and engineering",
    "CTO as a service",
    "startup software development company",
  ],
  markets: ["United States", "United Kingdom", "European Union", "United Arab Emirates", "Australia", "Canada"],
};
